/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as faucetSol from "./Faucet.sol";
export type { faucetSol };
export type { HumanAgentINFT } from "./HumanAgentINFT";
export type { MockOracle } from "./MockOracle";
