/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHumanAgentINFT,
  IHumanAgentINFTInterface,
} from "../../../contracts/Faucet.sol/IHumanAgentINFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "executor",
        type: "address",
      },
    ],
    name: "canUse",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "isVerified",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "ownerToTokenId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IHumanAgentINFT__factory {
  static readonly abi = _abi;
  static createInterface(): IHumanAgentINFTInterface {
    return new Interface(_abi) as IHumanAgentINFTInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHumanAgentINFT {
    return new Contract(address, _abi, runner) as unknown as IHumanAgentINFT;
  }
}
