/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as humanAgentInftSol from "./HumanAgentINFT.sol";
export type { humanAgentInftSol };
export type { MockOracle } from "./MockOracle";
