/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MockOracle,
  MockOracleInterface,
} from "../../contracts/MockOracle";

const _abi = [
  {
    inputs: [],
    name: "alwaysTrue",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "value",
        type: "bool",
      },
    ],
    name: "setAlwaysTrue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60806040526000805460ff1916600117905534801561001d57600080fd5b506101e98061002d6000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c8063223f5d6d1461004657806355c265fe14610069578063ee2d8f9414610090575b600080fd5b610067610054366004610102565b6000805460ff1916911515919091179055565b005b61007c61007736600461012b565b61009d565b604051901515815260200160405180910390f35b60005461007c9060ff1681565b6000805460ff16156100b1575060016100fc565b6001821480156100ea5750828260008181106100cf576100cf61019d565b9050013560f81c60f81b6001600160f81b031916600160f81b145b156100f7575060016100fc565b508015155b92915050565b60006020828403121561011457600080fd5b8135801515811461012457600080fd5b9392505050565b6000806020838503121561013e57600080fd5b823567ffffffffffffffff8082111561015657600080fd5b818501915085601f83011261016a57600080fd5b81358181111561017957600080fd5b86602082850101111561018b57600080fd5b60209290920196919550909350505050565b634e487b7160e01b600052603260045260246000fdfea2646970667358221220a149ff7264c403f72ca2eefecd1cf83613ee027e2a739232c2a7c3fabc9c586e64736f6c63430008180033";

type MockOracleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockOracleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockOracle__factory extends ContractFactory {
  constructor(...args: MockOracleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockOracle & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockOracle__factory {
    return super.connect(runner) as MockOracle__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockOracleInterface {
    return new Interface(_abi) as MockOracleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MockOracle {
    return new Contract(address, _abi, runner) as unknown as MockOracle;
  }
}
